GET /user/info HTTP/1.1
Host: localhost:8081
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjgwODEiLCJzdWIiOiI0IiwiaWF0IjoxNjk1ODg1ODY0LCJleHAiOjE2OTU5NzIyNjQsInR5cGUiOiJMIn0.ciy9gzqPjWsTTEEbWMBScDypC4lpaeDvCjifNAtwLTHUY82KfkKEmGZbTrTBCZowli2PSyWWRQ1VPyUwSJzhgg
Cookie: JSESSIONID=7ECE3A826EBA5C4BE2DD0B6D80BFDBE9;