spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://172.20.160.120:3308/local_test?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
        username: root
        password: 1qaz2wsx

    # redis相关配置
    redis:
        host: 172.20.160.120
        port: 6379
        password:
        database: 0
        jedis:
            pool:
                # 连接池最大连接数（使用负值表示没有限制）
                max-active: 8
                # 连接池最大阻塞等待时间（使用负值表示没有限制）
                max-wait: -1ms
                # 连接池中的最大空闲连接
                max-idle: 8
                # 连接池中的最小空闲连接
                min-idle: 0
        # 连接超时时间（毫秒）默认是2000ms
        timeout: 2000ms

server:
    port: 8081
#  servlet:
#    context-path: "/security"
#    application-display-name: Security

mybatis:
    mapperLocations: classpath:mapper/*.xml

# The signing key's size is 48 bits which is not secure enough for the HS512 algorithm.
# The JWT JWA Specification (RFC 7518, Section 3.2) states that keys used with HS512 MUST have a size >= 512 bits (the key size must be greater than or equal to the hash output size).
# Consider using the io.jsonwebtoken.security.Keys class's 'secretKeyFor(SignatureAlgorithm.HS512)' method to create a key guaranteed to be secure enough for HS512.
# See https://tools.ietf.org/html/rfc7518#section-3.2 for more information.

custom:
    jwtSecret: fd2d625a3b8c6c77d0d1937ee53bf8c63574a9f549435ad50f8e3a0786b67407
    jwtExpirationInMs: 86400000
    domain: http://localhost:8081